[[SCALAPACK32]]
arch = "aarch64"
git-tree-sha1 = "3d8f84b1b004aede506393aeb5b76672c3137483"
libgfortran_version = "5.0.0"
os = "macos"

    [[SCALAPACK32.download]]
    sha256 = "ebeb3166154cdef197e56d8a0a610decfa7690f739f85b7d63d88319c74cbc78"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[SCALAPACK32]]
arch = "aarch64"
git-tree-sha1 = "d8cc96d8dbc640315cd860d69db7b2cb5869b219"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "ee8fafc04d24a837a31f75bc635ef235084c557f359d52456a75c41e7a56d03e"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[SCALAPACK32]]
arch = "aarch64"
git-tree-sha1 = "69f5827b1edd31fb193e0f884b28e8e5b9101bb9"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "d1a8f11989aafb96dff6f23a809fe90175cae116db4dd69322e6ba47727a1f69"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[SCALAPACK32]]
arch = "aarch64"
git-tree-sha1 = "a964703b3ba1ec6ebf3b06f4249090b62d1a17a9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "e44329c4f1ed52f15d8356b7dc5ab735ac6a93c0893e332530e8a4092ef04277"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[SCALAPACK32]]
arch = "aarch64"
git-tree-sha1 = "1f99a56d11806b5b39dcf48d29a109081388c83d"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "90ecc643dbeca7a0f5c883d2d6e7d33f8a5ebe2100ccb4caeb346570b89ad61f"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[SCALAPACK32]]
arch = "aarch64"
git-tree-sha1 = "4b78f719d3775d1c5757f6bd7c75276fe4c36f4d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "34528a0a862b8155ea950420b446cbe0af9ac36e2dbf552c131c14d2421146ee"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[SCALAPACK32]]
arch = "aarch64"
git-tree-sha1 = "9a856363d6a9ada3e1a05fce4bb158c46516df38"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "5f6cb9806bb94d45adeb5ecb65e3f5c4357ca05b416f06d3ef75a14515b5afa3"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[SCALAPACK32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "21ceb73ec9ac2af3205b2ba45f6da91ca79b0593"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "6f0941f180c5afab52d12ca4dcbdb1cef3ca3d5de9dc20be1984ca834345c721"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[SCALAPACK32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ca9308aeedddd885d9da887e3bb288d5fc5e461e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "ec1def68b7ab65daa261cb12604fa7b6185d2e8667a58ffd5182cbfad244891e"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[SCALAPACK32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1a71dd2ab7275681a84c1dec6f39e07b06e284ee"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "156babe0a327ab9ad3f1f06903871851434c3e7f58badbf20c26936ac5da0b07"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[SCALAPACK32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e811ee7c934d7486b91a627cfd85243c3514be9a"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "41465a970e09563a235e237391b610546fdc7af9219b521c82693893d46ffb56"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[SCALAPACK32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8598689a45f949d977d8171f42320f9f5e6fb065"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "f0a6c9ebbf506341cf996b0c4d73867048b4c3d87d20d7dd90240a4b0d704af8"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[SCALAPACK32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a2f76fd9243b228c469970b1abd3b3aca985fa5d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "bbac7ec9f97141f33d780bf304c7143ba856a4588c5d051ead66bbc896e39613"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[SCALAPACK32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dda054b5b4aecf5389a801362387abf31471f3a7"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "e6a00756db3c5c5eb0ab929193ac6332f47a5e79ab66b5be451586daa0e6b83a"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[SCALAPACK32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "312579c970bcb1674e309bf781fbe8ebc4afd4ee"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "5abf6cc83f5cc9779ea3e3f56b9ca39b60aaf8c4748b54587f2b193eda2b1143"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[SCALAPACK32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "602bf8051ff0fdb3e9710e638e9bceb9522a7b00"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "f691ed7135ae3849fafa1b38e481e09a15fb6ce2113e51925a85199f00defb53"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[SCALAPACK32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "49340de81adf42ddddbee1a1a11425aa962e3018"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "54254c5f7201db20009e40bbc0c6d43ad09dc28633d17855944aafdd13093886"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[SCALAPACK32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7362cefa8d016aeb1e3fe7c26e1d44d3cb0ec825"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "810b51e04c7fdb708f4ceaa2ff35b24586c52ff1d062363a0f2f500414b107ae"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[SCALAPACK32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d1abbbce1156e4f2ecdfb5dfd554c574bbfe7026"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "30cebdd47b10d5ca68bee25b42ee9d6e38e79a617f2ef25df493112939705ebf"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[SCALAPACK32]]
arch = "i686"
git-tree-sha1 = "bb34b007a6105a9425750d177434f8a3716c025c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "75793f90e5dae90165b78a51cbd880e4b96df7bb4ae60f220639c85597795c81"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.i686-linux-gnu-libgfortran3.tar.gz"
[[SCALAPACK32]]
arch = "i686"
git-tree-sha1 = "07a49e570aaade8834ff5ea83b3de97ac4f7e6fe"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "b9556f5070b3d5c2ea1a831f20cb6236937744a0b6c1873fcf42d2e5adfeec07"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.i686-linux-gnu-libgfortran4.tar.gz"
[[SCALAPACK32]]
arch = "i686"
git-tree-sha1 = "f5c55359c9978231e88726fa98706ee74c7e0508"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "877181027f06253249e5aebd972601fe1f9a17e42e442da9908443f8dfcf19cf"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.i686-linux-gnu-libgfortran5.tar.gz"
[[SCALAPACK32]]
arch = "i686"
git-tree-sha1 = "5988e63ac101563a0d5f2f481ccf0fabc0c7d1ac"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "faa7e84e5708738efdf46c13b7325f686b6120a2a0ac6a3c6f61d799ca39062d"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.i686-linux-musl-libgfortran3.tar.gz"
[[SCALAPACK32]]
arch = "i686"
git-tree-sha1 = "7811cc61051cbb1550825f239df1e4e88311f3ef"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "766d77cf4eb49237854d7f591457fd2be4600a6533e8228a8d668b9165336086"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.i686-linux-musl-libgfortran4.tar.gz"
[[SCALAPACK32]]
arch = "i686"
git-tree-sha1 = "3bcf84d9e5fe4b28ac04169fe2c2f7941796aab1"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "c73ea43d18028deeb4245cb4fb5cb1e15c7de4506541bad8f760f97c387f02d1"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.i686-linux-musl-libgfortran5.tar.gz"
[[SCALAPACK32]]
arch = "powerpc64le"
git-tree-sha1 = "e15e1f92e5959bfaa013ec3e7285393ed7792cad"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "41d74bb332928b8a9e4dac73c45cfb656213f55aaacac88700f745e42df64d9e"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[SCALAPACK32]]
arch = "powerpc64le"
git-tree-sha1 = "abca99df145ab822d7a5efe2b79409d9d4c5d788"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "9de4fbd17497baa79e098c81b3f9a315bef5b3700c882f8471495ed265a82a9c"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[SCALAPACK32]]
arch = "powerpc64le"
git-tree-sha1 = "f8f6ce7eb7741f115c9a7039de6bdab3911267e3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "5b8e9ad8f5ea64d6464034a8238a8af317005030aa28ff95c7e83c3afc208236"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[SCALAPACK32]]
arch = "x86_64"
git-tree-sha1 = "db0d0238659363fdf7e8424a3f535ed5f64e1595"
libgfortran_version = "3.0.0"
os = "macos"

    [[SCALAPACK32.download]]
    sha256 = "4822979ce425453245dc5299dec1e215e23bfd368a815d50b128908b186231fa"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[SCALAPACK32]]
arch = "x86_64"
git-tree-sha1 = "d1fcbc982979fe2bd2f55d478ebc35d9e9527d89"
libgfortran_version = "4.0.0"
os = "macos"

    [[SCALAPACK32.download]]
    sha256 = "ec2b18c8db6b44a0d40bdd9dce49d03fb1404927fdef8137a195c866dbe2e75e"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[SCALAPACK32]]
arch = "x86_64"
git-tree-sha1 = "828888214e667769847a98455ab09c23499babf9"
libgfortran_version = "5.0.0"
os = "macos"

    [[SCALAPACK32.download]]
    sha256 = "f8994dedc18946d1520c2ce82d744021ff77c0364cc3bc489c96ee4d7615da84"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[SCALAPACK32]]
arch = "x86_64"
git-tree-sha1 = "8494430d95901af1434e6f12856229868722a698"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "787628b6d061cca337f8d4fef6b38abce6d419f7df9986f1cbcccac2ee2bfd0b"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[SCALAPACK32]]
arch = "x86_64"
git-tree-sha1 = "c2e059683c562154736f3ce883c140bd0fbdb040"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "f1fa3141f0966bee58f05909dba2c698943eb9442790bc962a2b6b13b729cfb4"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[SCALAPACK32]]
arch = "x86_64"
git-tree-sha1 = "e65ed3a3d19c78d970f7bded90f39185bbdbd0e8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "c718649894be7a1dfc01445e828ff0acb2f449f3151ae6c0d2f86669d2851269"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[SCALAPACK32]]
arch = "x86_64"
git-tree-sha1 = "0e54013173e7263e7a2fb4cb22edff44b64d1673"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "582b28a0b0f014106ef92fdc987f925b9996a1dd78eb73bf18731de4d2133b7f"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[SCALAPACK32]]
arch = "x86_64"
git-tree-sha1 = "a8fffc9739f07f6589035eb497cf250efccfd3b4"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "12fba33fdb227c9dd890f2cccbd05627e06bceae36e13616b9ed643eebd2aada"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[SCALAPACK32]]
arch = "x86_64"
git-tree-sha1 = "0fc42c6d84d07b273dc3d1f46bcaba9803dba916"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "bc5c00fa93521c8ae8e97e5cffed38ba67abe0935829ac50099bd721dae9b6f4"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[SCALAPACK32]]
arch = "x86_64"
git-tree-sha1 = "d4931cea3d63c0d0480aa28d45b52ad137b4c49c"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[SCALAPACK32.download]]
    sha256 = "ca1b32e34c83fc3a5924dce3bf22824c0312716516d8c81119a5a8d0673955dd"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[SCALAPACK32]]
arch = "x86_64"
git-tree-sha1 = "a9fe027fd73be79eb91f3c26cad214e13df0a765"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[SCALAPACK32.download]]
    sha256 = "76a762e052c547fdfb5759ad735d43dfcb493e4a1476fa09102c346ee6f795b8"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[SCALAPACK32]]
arch = "x86_64"
git-tree-sha1 = "55bc7905908765ce42463e5843deaea6cd26d71f"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[SCALAPACK32.download]]
    sha256 = "cc2f2fad97d0a0553ee7d76e4b69439f78d3b7f4a5658222f23c390210dfe2fe"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.2.0+0/SCALAPACK32.v2.2.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
